apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: demo-app-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: demo-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: WELCOME_MESSAGE
      remoteRef:
        key: ct-gitops/dev/demo-app
        property: WELCOME_MESSAGE