apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-app-secret
spec:
  # How often ESO should re-check the provider (does NOT rotate the provider secret by itself)
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: demo-app-secrets
    creationPolicy: Owner

  data:
    - secretKey: WELCOME_MESSAGE
      remoteRef:
        key: ct-gitops/dev/demo-app
        property: WELCOME_MESSAGE