apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ct-gitops

  source:
    repoURL: "https://github.com/tanmayj-hub/gitops-eks-apps.git"
    targetRevision: "main"
    path: "apps/demo/overlays/dev"

  destination:
    server: "https://kubernetes.default.svc"
    namespace: "demo"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true